// module/giphy state
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const SET_ACTIVE_GIF = 'SET_ACTIVE_GIF'
export const SET_ACTIVE_GIF_INDEX = 'SET_ACTIVE_GIF_INDEX'
export const SET_FAVORITES = 'SET_FAVORITES'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
